source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'EapthMap_Example' do
  
  pod 'EpathMap', :path => '../'
  pod 'WechatOpenSDK'
  pod 'Bugly', '~>2.4.8'
  pod 'Mixpanel', '~>3.1.9'
  pod 'Parse', '~>1.14.4'
  pod 'SDWebImage', '~>3.8.2'
  pod 'SVProgressHUD', '~>2.1.2'

end
